export const images = {
  logo: require("./images/logo.png"),
  profile_overlay: require("./images/profile_overlay.png"),
  defaultImg: require("./images/defaultImg.png"),
  sadCart: require("./images/sad-cart.png"),
  happyCart: require("./images/happy-cart.png"),
  pizza: require("./images/pizza.png"),
  bacon: require("./images/bacon.png"),
  bifteck: require("./images/bifteck.png"),
  chicken: require("./images/chicken.png"),
  ice: require("./images/ice.png"),
  salad: require("./images/salad.png"),
  burger: require("./images/burger.png"),
  promo: require("./images/promo.png"),
  promo1: require("./images/promo1.png"),
  promo2: require("./images/promo2.png"),
  promo3: require("./images/promo3.png"),
  promo4: require("./images/promo4.png"),
};
